---
version: '3.1'
services:
  watchlist:
    image: watchlist:latest
    restart: always
    container_name: watchlist
    ports:
      - 5000:5000
    environment:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_DB_NAME: watchlist
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456